### ISSUE TITLE
A Beginner's Request

### ISSUE THREAD

**Issue by Lorindellia** [github/training-kit#316]
Dear GitHub Training,

I have used github before to simply modify a java thing for minecraft.  I had total step by step instructions. 

Now, I want to learn how to create my own programs using github, but other than the above I haven't programmed a thing in my life.

I tried to complerte the lesson that gives out badges but it crashed and I can't get it back...

I would very much like it if you could possibly create new forks for the different training leves, in one file pocket, like Begin here, Intermediate here, and advanced here...

Also, if possible, can these be further divided by language?

No, Not Eng Fr Spa; but C++ Python, Java... etc?

Can anyone help?
Leah

**Comment by jordanmccullough** [comment]
Hi Leah,

Our GitHub Training Kit is programming language agnostic, allowing the focus to remain on Git and GitHub processes, rather than a particular tech stack.

While we have some improvements in mind for the curriculum, the current structure of *Foundations*, *Intermediate*, and *Advanced* aligns with our [classes](https://training.github.com/classes) and has proven useful to students participating in these events.

If you're seeking more guide-like tutorials for using Git and GitHub, give our YouTube channel a look. The videos there cover all day-to-day Git commands, and a number of webcasts on GitHub related topics. All this is available here: https://youtube.com/githubguides

Thanks for the feedback, and best of luck on exploring Git, GitHub, and software programming. 

:octocat:
