### ISSUE TITLE
Got 404 Page Not Found

### ISSUE THREAD

**Issue by wisn** [github/training-kit#408]
I'm trying to access https://services.github.com/kit/, but I got `404 Page Not Found`.
The GitHub System Status told me that all system operational.
Is it moved? Or something happens?

Screenshot
![screenshot from 2016-11-20 08-03-17](https://cloud.githubusercontent.com/assets/8147926/20459749/c531de16-aeff-11e6-8ba8-a91998d5889e.png)

**Comment by jayvdb** [comment]
I think it is now here : https://services.github.com/on-demand/
But only some courses are enabled, and the "Open Chat" links go to https://gitter.im/githubschool for https://github.com/githubschool

But it is a bit confusing because there is also https://github.github.io/on-demand/

**Comment by crichID** [comment]
@wisn and @jayvdb thank you for noticing and bringing this to our attention! 

We are in the process of open sourcing our newest generation of courses. These resources were initially being developed at https://github.github.io/on-demand but we will be deprecating that closed source repo in favor of this one. 

> I think it is now here : https://services.github.com/on-demand/

@jayvdb you are correct - this will be the new home for the rendered courses.

> But only some courses are enabled

We are moving the remaining courses as quickly as possible, but would also welcome any assistance in re-formatting the old courses. In fact, I may go ahead and open issues to that effect later this week!

**Comment by matthewmccullough** [comment]
@crichID and Training team: If the https://services.github.com/kit/ URL is deprecated, can we put in a temporary redirect to help route folks over to https://services.github.com/on-demand/ or another preferred location, just to help folks discover our new home for materials?

**Comment by brntbeer** [comment]
Is https://services.github.com/kit/ suppose to redirect to https://services.github.com/on-demand/ or https://services.github.com/resources/? The `kit/` endpoint previously was where we showed the cheatsheet as well as links to open source material about the classes.

If the `on-demand/` material will end up being linked to from `resources/`, my vote would be to redirect `kit/` to `resources/`, but that's just my opinion! This would also be helpful since `resources/` is a part of our top-level navigation, and `kit/` used to be a part of that navigation.

**Comment by crichID** [comment]
> Is https://services.github.com/kit/ suppose to redirect to https://services.github.com/on-demand/ or https://services.github.com/resources/? The kit/ endpoint previously was where we showed the cheatsheet as well as links to open source material about the classes.

@brntbeer great questions! The cheatsheets etc. are actually linked from https://services.github.com/resources. The /kit endpoint has been "hidden" on services.github.com since the re-design earlier in the year.

> If the on-demand/ material will end up being linked to from resources/, my vote would be to redirect kit/ to resources/, but that's just my opinion! This would also be helpful since resources/ is a part of our top-level navigation, and kit/ used to be a part of that navigation.

The on-demand material is being linked on /training and on the home page, but not on /resources.

**Comment by brntbeer** [comment]
@crichID sounds fine to me! just happy with a decision
