### ISSUE TITLE
Labels for issues and pull requests

### ISSUE THREAD

**Issue by brianamarie** [github/training-kit#420]
To help contributors sort through and understand existing issues and pull requests, I'd like to add some different labels. This is linked to the [Open Source Community Updates](https://github.com/github/training-kit/issues/415) issue. 

Ideas: 

**Type of Issue or PR:**
- Bug
- New Feature
- New Course
- Translation

**Skillset Needed:**
- HTML/CSS
- Jekyll
- Content Writing
- Design
- Video
- Review/Testing
- No Code Required

**Other**
- good-first-patch
- up-for-grabs
- Duplicate
- Won't Fix

@github/services-training What are some other ideas we could include? I'd ❤️ to ship an iteration of this by Friday, December 9. 

**edit by @hectorsector:** update label list with suggestions that emerged from the thread

**Comment by beardofedu** [comment]
@brianamarie if we are going to differentiate between 'writing' and 'technical writing' we might want to identify a 'Creative Writing' label. If we do create a 'Creative Writing' label, do we need a 'Content Request' label? Additionally, we should provide definitions for the different labels within the README / CONTRIBUTING file _or_ in a Wiki. 

I'm on the fence about grouping the labels into categories, but I can't mentally picture how I would want to group them because something like this might occur:
- a BUG with Technical Writing
- Help Wanted with Technical Writing
- an Enhancement with Technical Writing

So creating a 'HW: Technical Writing' doesn't cover all of our bases. Just a thought I wanted to throw out there and perhaps someone else might be able to refine it.

**Comment by brntbeer** [comment]
> HW: Technical Writing

Also, just throwing this out there. Please spell out everything and don't use acronyms. They make me sad and easily confused 😸 

(_Brought to you by the Brntbeer Foundation For Bringing the Eventual Death to Acronyms (BBFFBEDA)_)

**Comment by hectorsector** [comment]
One potential benefit: multiple labels can be applied. So if there's a bug with technical writing, both `bug` and `technical writing` can be applied!

👍 on label definitions in documentation
👍 for 🚢 a short list of labels first, and expanding them as needed
👍 on the prelim list of labels

**Comment by crichID** [comment]
> _(Brought to you by the Brntbeer Foundation For Bringing the Eventual Death to Acronyms (BBFFBEDA))_

@brntbeer :heart:

My brain finds it easier to think of our labels in groupings - does this make sense to anyone else?

**Type of Issue or PR:**
- Bug
- New Feature
- New Course
- Translation

**Skillset Needed:**
- HTML/CSS
- Jekyll
- Content Writing
- Design
- Video
- Review/Testing
- No Code Required

**Other**
- Duplicate
- Won't Fix

P.S. I don't :heart: the help wanted label - does that mean we don't want help on the other stuff? To me, all issues and PRs are help wanted!

**Comment by hectorsector** [comment]
👍 I'm happy with that, @crichID. Could we identify the grouping by color coding? I.e. all "type of issue/pr" labels are shades of orange, all "skill set needed" labels are shades of purple, all "other" labels are shades of gray?

@brianamarie if you'd like me to move forward with implementing this I can do so

**Comment by beardofedu** [comment]
@crichID thank you for creating a grouping strategy that makes sense 😄 

I think this is a great start for labels.

**Comment by hollenberry** [comment]
I ❤️ all of the above discussion and labels. This is excellent! 

I think that we might also benefit from a few labels like...
- [up-for-grabs](http://up-for-grabs.net/#/)
- Claimed (this might be a redundancy if we implement the above with consistency)
- [first-timers-only](http://www.firsttimersonly.com/)

**Comment by beardofedu** [comment]
@hollenberry I like the idea of 'up-for-grabs' and maybe changing 'first-timers-only' to 'first-timer-friendly'. I think 'claimed' might prevent people from trying to help resolve an issue with other people if they see that the issue is claimed, but overall 👍

**Comment by hollenberry** [comment]
> I think the comprehensive walkthrough is good, as well as the first-timers-only 👍, but I'd like to lower the barrier of entry for anyone and not impose a restriction that we'll only accept PRs from first-timers.

> I like the idea of 'up-for-grabs' and maybe changing 'first-timers-only' to 'first-timer-friendly'. I think 'claimed' might prevent people from trying to help resolve an issue with other people if they see that the issue is claimed, but overall 👍

I definitely see where both of you are coming from, @beardofedu @hectorsector . I liked the idea of `first-timers-only` because we'd get increased traffic from people who find our repository via the website, but in following up I'm not sure how heavily trafficked the label/referral site is. 

Ultimately, I'm happy to forego it, but I imagine that we'd apply this to incredibly minor labels that are easy to snap up (change the copyright year to 2017, etc) by advanced users and would be nice to `reserve` for trepidatious beginners (since this is a large part of our audience).  

Thoughts?

I'm also happy to forego 'claimed'. It might be nice for issues with a singular assignee, but probably creates a closed door culture that we don't want.

**Comment by crichID** [comment]
> up-for-grabs

@hollenberry I love the idea of this site and think it might be a cool way to drive engagement. I think there are other ways too, like being added to a github showcase for beginner friendly projects. I :heart: that we are considering these other methods of connecting in the community.

> I'm also happy to forego 'claimed'. It might be nice for issues with a singular assignee, but probably creates a closed door culture that we don't want.

:+1: agreed this is redundant and might create a closed door culture

> first-timers-only

@kytrinyx [recommended using `good-first-patch` as an alternative to this](https://github.com/github/training-kit/issues/415#issuecomment-265228647). I really like her suggestion!

**Comment by hectorsector** [comment]
I updated the OP with the current suggestions.

**Comment by brianamarie** [comment]
😍 This is looking so fabulous! Thank you @beardofedu @brntbeer @hectorsector @hollenberry & @crichID! 

What are your thoughts of trying out the current labels in the updated original post?

**Comment by crichID** [comment]
> What are your thoughts of trying out the current labels in the updated original post?

:+1: Let's do it!

**Comment by brianamarie** [comment]
Woohoo! Closing now as labels have been added and modified. We can iterate on this as needed! 🎉
