### ISSUE TITLE
Git Out of Trouble is in Trouble (Broken Links)

### ISSUE THREAD

**Issue by hollenberry** [github/training-kit#484]
Received an e-mail via services@github with the following feedback (format updates are mine to make discussion points clear). 

### Broken Links
```
Hi, I just breezed through the great and concise training and enjoyed it.

* I had GitHub training elsewhere, so this was not totally new to me, but seemed to be a very good fast-start collection.

I got to the Git Out Of Trouble section - https://services.github.com/on-demand/git-trouble/git-scenarios.

* On the Git Trouble Scenarois page (https://services.github.com/on-demand/git-trouble/git-scenarios), there are a few broken links.

Too Many (small) Commits!<https://services.github.com/on-demand/git-trouble/03>

* Points to https://services.github.com/on-demand/git-trouble/03 and gets 404 - File not found

* From left-panel it seems the link should be https://services.github.com/on-demand/git-trouble/too-many-commits intead

Other ones are also similarly broken
Commit Message Sucks<https://services.github.com/on-demand/git-trouble/04>
* Should be https://services.github.com/on-demand/git-trouble/git-commit-message

Commit to Wrong Branch<https://services.github.com/on-demand/git-trouble/05>
* Should be https://services.github.com/on-demand/git-trouble/git-commit-wrong-branch
Accidental Commit<https://services.github.com/on-demand/git-trouble/06>
* Should be https://services.github.com/on-demand/git-trouble/accidental-git-commit
Just Make it Go Away!<https://services.github.com/on-demand/git-trouble/07>
* Should be https://services.github.com/on-demand/git-trouble/breaking-things-with-git
```

### Discussion Points
```
I like the idea of the left panel navigation, but wonder a few things:

* Should the names in the panel match the ones listed exactly (the left panel uses "Git" in the names but the right doesn't and it makes me wonder if I'm missing something

* Should the left panel names start some separator to make them easier to distinguish (then almost ran together)

* Should the left panel "close up" entries under Git Trouble Scenarios when the user is viewing the page for Set Up your Git Scenario Environment? (https://services.github.com/on-demand/git-trouble/git-set-up)
```

Next Steps:
- I'll open a PR to fix these broken links.
- @beardofedu do you have any thoughts on the discussion points? I think they're pretty solid ideas. If I recall correctly, you and @hectorsector have adjusted the left panel in the past. Are these changes (collapsing and clear separation) possible?

**Comment by beardofedu** [comment]
@hollenberry 
I think this occurred when we fixed the links to be more SEO aware (findable?). We should fix this, and if you need me to I can, but I know you self-assigned / I think I saw a `commit` get pushed through while writing this...

### Discussion Points
- Git was added for SEO and _should_ be added to the left panel
- We might be able to get the stylesheet to alternate colors or something ... might be a useful Issue to create and see if this individual or @r5atom are interested in trying to tackle it 😉 
- I'm unfamiliar with the ability to collapse menu options, however, since we don't use multiple sub-sections, it might be unnecessary, if our content was exceeding the length of the page, I would 👍  the development of collapsing drop-downs.

**Comment by hollenberry** [comment]
> Git was added for SEO and should be added to the left panel

Should we add it to the scenario page titles? 

![screen shot 2017-03-08 at 1 20 31 pm](https://cloud.githubusercontent.com/assets/13326548/23724571/0c3d7e26-0402-11e7-9504-326e81a62a2c.png)

> We might be able to get the stylesheet to alternate colors or something ... might be a useful Issue to create and see if this individual or @r5atom are interested in trying to tackle it 😉

This sounds great! I reached out to the user who e-mailed to ask if he wanted to create this issue/PR-fix, and gave him a day to do so. Since we can't leave the links broken, I love this as an extension. 

> I'm unfamiliar with the ability to collapse menu options, however, since we don't use multiple sub-sections, it might be unnecessary, if our content was exceeding the length of the page, I would 👍 the development of collapsing drop-downs.

👍  I like it because it'd make things look tidy on any course. Maybe we can open another issue on this for someone to tackle.

**Comment by beardofedu** [comment]
1. Yes, they should match.
2. In regards to the drop-downs, this is the only course that is _currently_ using them, as an FYI.

**Comment by hollenberry** [comment]
> In regards to the drop-downs, this is the only course that is currently using them, as an FYI.

I'd actually love to make this a thing on the OS course, too. That was the original intent for sections like "Contributing" that are hard to write content for, but good as headers.

**Comment by EricVook** [comment]
Looks good. Of course verification will be easier when updates hit the [URL](https://services.github.com/on-demand/git-trouble/git-scenarios). :smile_cat:

**Comment by hectorsector** [comment]
I love the witty title, @hollenberry!

@beardofedu @hollenberry it appears that there are still links that 404, ☝️. Thanks for noticing @EricVook. I'm going to reopen this issue until we can get that taken care of.

Additionally, our CI tests should be catching broken links, shouldn't they? Seeing as the [last CI build didn't catch the broken links](https://travis-ci.org/github/training-kit/builds/209128244) we should look into what's going on there, too.

**Comment by brianamarie** [comment]
> Additionally, our CI tests should be catching broken links, shouldn't they? Seeing as the last CI build didn't catch the broken links we should look into what's going on there, too.

I don't _think_ we have tests in place to check for valid HTML on training-kit. :bowtie: I will open an issue about this.

![](https://media.giphy.com/media/W9wHF6yVazlrW/giphy.gif)

**Comment by hollenberry** [comment]
> I'm going to reopen this issue until we can get that taken care of.

Hey @hectorsector !! Thank you for re-opening! I intended to merge this into services-web as soon as #486 is merged in. 

Are there any other links to fix in the meantime?

**Comment by crichID** [comment]
> I intended to merge this into services-web as soon as #486 is merged in.

@hollenberry with bug fix type PRs, it is probably best not to hold up making the updates to services-web while we wait for non-urgent PRs. I know it is an extra review, but smaller :ship:s are easier to sail :wink:

**Comment by hollenberry** [comment]
> with bug fix type PRs, it is probably best not to hold up making the updates to services-web while we wait for non-urgent PRs. I know it is an extra review, but smaller 🚢s are easier to sail 😉

This is a good point. 👍 I'll do the right thing next time 😄

**Comment by r5atom** [comment]
> We might be able to get the stylesheet to alternate colors or something ... might be a useful Issue to create and see if this individual or @r5atom are interested in trying to tackle it 😉

Would it be as simple as adding

`ul ul { margin: 10pt; }`

here `_stylesheets/_navigation.scss`
or here `_stylesheets/_sidebar.scss`

❓

**Comment by hectorsector** [comment]
> Would it be as simple as adding

@r5atom the template we use for on-demand content is called [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/). The left panel is explained in Minimal Mistakes' [navigation documentation](https://mmistakes.github.io/minimal-mistakes/docs/navigation/), as well as the [custom side navigation documentation](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu). I'd start looking there, and if it doesn't get you to what you're looking to do, then maybe try changing the stylesheet.

Heads up: I think you'll really need to be able to spin up a local copy of the site on your machine to collaborate on this one so if you have any trouble at all doing that just holler. 

> * Should the left panel names start some separator to make them easier to distinguish (then almost ran together)
> * Should the left panel "close up" entries under Git Trouble Scenarios when the user is viewing the page for Set Up your Git Scenario Environment? (https://services.github.com/on-demand/git-trouble/git-set-up)
>> We might be able to get the stylesheet to alternate colors or something ... might be a useful Issue to create

@beardofedu @hollenberry @r5atom agreed, this can be a separate issue since it falls outside of the 404 fix in this one. I'll go ahead and close it out, since the fixes are [now live](https://services.github.com/on-demand/git-trouble/git-scenarios).

**Comment by EricVook** [comment]
The links look great now. (LGTM)

The [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/) template seems to assume _short_ titles for sub-sections.
- Longer titles create confusion because of wrapping.
- Can we arrange for a separator symbol (like a bullet) to be part of our titles without changing the template?

**Comment by beardofedu** [comment]
@EricVook this would become a style discussion, we typically try to match the headings at the top of a topic to the name listed in the side nav, it might be possible for us to provide a shorter description name... 

As far as the bullet / separator, that might be something we can look into.
