### ISSUE TITLE
Add link to https://services.github.com/on-demand to cheatsheet

### ISSUE THREAD

**Issue by izahn** [github/training-kit#647]
## Overview
**TL;DR**
There is a link at the bottom of `github-cheat-sheet.pdf` to training.github.com, but no link to https://services.github.com/on-demand. It would be good to have a link at the bottom of the cheatsheet so people know where to go for more resources.

### Extra Detail
I couldn't figure out where the footer comes from (it does not appear in `github-cheat-sheet.md`), hence this issue rather than a pull request...

**Comment by brianamarie** [comment]
Thank you for opening this issue, @izahn. You're 💯 correct! Since the PDF is managed and printed internally at GitHub, and then the source file is updated in this repository, I'm going to move this conversation to a different repository within GitHub (that will be private). Hopefully we will be able to push an update soon. Thank you again! ✨
